[package]
name = "rpgmtranslate_rs"
version = "1.0.0"
edition = "2024"
publish = false

[lib]
name = "rpgmtranslate_rs"
crate-type = ["staticlib"]

[features]
languagetool = []
json-highlighting = ["lumis/lang-json"]
js-highlighting = ["lumis/lang-javascript"]
ruby-highlighting = ["lumis/lang-ruby"]
js-formatting = ["dep:dprint-plugin-typescript", "dep:anyhow"]
ruby-formatting = ["dep:rubyfmt"]

[dependencies]
deepl = "0.8.1"
gxhash = { version = "3.5.0", features = [
    "deterministic",
], default-features = false }
language-tokenizer = { version = "0.3.1", features = ["full"] }
languagetool-rust = { version = "3.0.1", default-features = false, features = [
    "native-tls",
] }
keyring = "4.1.6"
llm-connector = "1.4.0"
log = "0.4.33"
lumis = { version = "0.13.0", default-features = false, optional = true }
marshal-rs = "2.0.1"
regex = "1.13.1"
reqwest = { version = "0.12", default-features = false, features = [
    "native-tls",
] }
rpgm-asset-decrypter-lib = "3.2.2"
rpgmad-lib = "5.0.0"
rvpacker-txt-rs-lib = { version = "14.0.0", features = [
    "serde-csv",
    "serde-xml",
    "serde-xlsx",
    "serde-yaml",
] }
serde = "1.0.229"
serde-transcode = "1.1.1"
serde_json = "1.0.151"
thiserror = "2.0.20"
tokio = "1.53.1"
translators = { version = "0.2.0", features = ["google", "tokio-async"] }
yandex-translate-v2 = { version = "0.1.3", features = [
    "async",
], default-features = false }
dprint-plugin-typescript = { version = "0.96.1", optional = true }
anyhow = { optional = true, version = "1.0.104" }
rubyfmt = { version = "0.14.1", optional = true, path = "./librubyfmt" }
[profile.release]
lto = "fat"
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
opt-level = 3
panic = "abort"
strip = "symbols"

[profile.release.build-override]
debug = false
debug-assertions = false
overflow-checks = false
codegen-units = 1
opt-level = 3
strip = "symbols"
