language = "C++"
pragma_once = true
include_version = false
no_includes = true
cpp_compat = true
includes = ["FWD.hpp", "Enums.hpp"]
sys_includes = ["cstdint"]

braces = "SameLine"
line_length = 80
tab_width = 4
documentation = true
line_endings = "LF"

[parse]
parse_deps = true
include = ["language-tokenizer", "rvpacker-txt-rs-lib"]
clean = true

[export]
include = [
    "FFIString",
    "ByteBuffer",
    "LogCallback",
    "FileFlags",
    "RPGMFileType",
    "MatchMode",
    "HighlightToken",
    "HighlightLanguage",
    "ReadMode",
]
exclude = ["Bitset2048", "Selected"]
item_types = ["functions", "structs", "enums", "typedefs", "constants"]

[layout]
packed = "assert"
aligned_n = "assert"

[enum]
add_sentinel = false
derive_helper_methods = false
must_use = "[[nodiscard]]"

[fn]
rename_args = "snake_case"
must_use = "[[nodiscard]]"

[struct]
rename_fields = "snake_case"
derive_constructor = false
derive_eq = true
derive_neq = false
derive_lt = false
derive_lte = false
derive_gt = false
derive_gte = false
must_use = "[[nodiscard]]"

[macro_expansion]
bitflags = true

[defines]
"feature = languagetool" = "ENABLE_LANGUAGETOOL"
"feature = json-highlighting" = "ENABLE_JSON_HIGHLIGHTING"
"feature = js-highlighting" = "ENABLE_JS_HIGHLIGHTING"
"feature = ruby-highlighting" = "ENABLE_RUBY_HIGHLIGHTING"
